name: zbuild_operon

on:
  push:
    branches:
      - zbuild_operon_aki

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'centos:7'

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          echo "Install dependencies"
          yum -y install curl bzip2 git which patch

          echo "Install miniconda"
          curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
          bash /tmp/miniconda.sh -b -p $HOME/miniconda
          eval "$($HOME/miniconda/bin/conda shell.bash hook)"
          
          echo "create and activate conda environment" 
          conda env create -f build_operon/py37.yml
          conda activate operon-env
          
          echo "Conda Pack"
          conda install -y conda-pack          
                    
          echo "Cloning & Building the operon"
          git clone https://github.com/heal-research/operon.git
          mv build_operon/py37.yml operon
          cd operon
          
          
          ### Oct 7 version : working  https://github.com/heal-research/operon/commits/          
          git checkout fa729cf99e4a3ccbbf6886a370f646bac7fc734f

          # Apply patch before build
          patch -p1 < ../CMakeLists.txt.patch
          # patch -p1 < ../no-avx2-no-fma.patch  # if CPU does not have AVX2 or FMA
          
          
          #### Build  ##############################
          which gcc 
          which cmake
                    
          # run cmake with options
          mkdir build; cd build;
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_PYBIND=ON \
            -DUSE_OPENLIBM=ON \
            -DUSE_SINGLE_PRECISION=ON \
            -DCERES_TINY_SOLVER=ON
          make VERBOSE=1 pyoperon
          make install
          
          #### Check
          python -c "from operon.sklearn import SymbolicRegressor"
          
          
          ### Pack the install env
          conda pack -n operon-env  -o conda_operon_env.tar.gz
          
 
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: conda-operon-env
          path: 'conda_operon_env.tar.gz'
          retention-days: 120
