name: zbuild_operon

on:
  push:
    branches:
      - zbuild_operon_aki

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'centos:7'

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          echo "Install dependencies"
          yum -y install curl bzip2 git which patch

          echo "Install miniconda"
          curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
          bash /tmp/miniconda.sh -b -p $HOME/miniconda
          eval "$($HOME/miniconda/bin/conda shell.bash hook)"
          
          echo "create and activate conda environment" 
          conda create -n operon-env python=3.7 conda-build
          conda activate operon-env
          
          ### Oct 7 version : working  https://github.com/heal-research/operon/commits/          
          # git checkout fa729cf99e4a3ccbbf6886a370f646bac7fc734f
          
          #### Build  ##############################
          cd build_operon
          conda build -c conda-forge recipe
 
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: upload files
          path: /github/home/miniconda/envs/operon-env/conda-bld/linux-64/operon-*-py*.tar.bz2
          retention-days: 300
