name: zbuild_operon

on:
  push:
    branches:
      - zbuild_operon

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'centos:7'

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          echo "Install dependencies"
          yum install libXcomposite libXcursor libXi libXtst libXrandr alsa-lib mesa-libEGL libXdamage mesa-libGL libXScrnSaver centos-release-scl ca-certificates wget epel-release g++ gcc-c++ git python3 -y
          
          echo "Install GCC"
          yum install devtoolset-9 -y
          source /opt/rh/devtoolset-9/enable
          
          echo "Install CMake"
          export CMAKE_VERSION=3.12.4
          curl -fsSLO --compressed https://cmake.org/files/v3.12/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
          curl -fsSLO --compressed https://cmake.org/files/v3.12/cmake-${CMAKE_VERSION}-SHA-256.txt.asc
          curl -fsSLO --compressed https://cmake.org/files/v3.12/cmake-${CMAKE_VERSION}-SHA-256.txt
          tar xzf cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz -C /usr/local --strip-components=1 --no-same-owner



          echo "Install miniconda"
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
          eval "$($HOME/miniconda/bin/conda shell.bash hook)"
          
          echo "create and activate conda environment" 
          conda env create -f build_operon/py37.yml
          conda activate operon-env
          
          echo "Conda Pack"
          conda install -y conda-pack          
          
          


          echo "Install required dependencies for operon"
          yum install ceres-solver fmt doctest-devel -y
          echo "Cloning & Building the operon"
          git clone https://github.com/heal-research/operon.git
          mv build_operon/py37.yml operon
          cd operon
          

          
          #### Build  ##############################
          export CC=gcc
          export CXX=gcc
          
          # run cmake with options
          mkdir build; cd build;
          cmake .. -DCMAKE_BUILD_TYPE=Release  -DBUILD_PYBIND=ON -DUSE_OPENLIBM=ON -DUSE_SINGLE_PRECISION=ON -DCERES_TINY_SOLVER=ON
          make VERBOSE=1 -j pyoperon
          make install
          
          
          ### Pack the install env
          conda pack -n operon-env  -o conda_operon_env.tar.gz
          
 
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: conda-operon-env
          path: 'conda_operon_env.tar.gz'
          retention-days: 120
